// The quiz set: 193 UN members + Vatican City, Palestine, Kosovo, Taiwan.
// [display name, name used in the world-atlas data, region, accepted alternate answers]
// Everything else on the map (Greenland, Puerto Rico, Western Sahara, …) is drawn as grey context.
export const COUNTRIES = [
  // ── Africa ──
  ['Algeria', 'Algeria', 'Africa'],
  ['Angola', 'Angola', 'Africa'],
  ['Benin', 'Benin', 'Africa'],
  ['Botswana', 'Botswana', 'Africa'],
  ['Burkina Faso', 'Burkina Faso', 'Africa'],
  ['Burundi', 'Burundi', 'Africa'],
  ['Cabo Verde', 'Cabo Verde', 'Africa', ['Cape Verde']],
  ['Cameroon', 'Cameroon', 'Africa'],
  ['Central African Republic', 'Central African Rep.', 'Africa', ['CAR']],
  ['Chad', 'Chad', 'Africa'],
  ['Comoros', 'Comoros', 'Africa'],
  ['Democratic Republic of the Congo', 'Dem. Rep. Congo', 'Africa', ['DR Congo', 'DRC', 'Congo Kinshasa', 'Congo', 'Zaire']],
  ['Republic of the Congo', 'Congo', 'Africa', ['Congo Brazzaville', 'Congo']],
  ['Djibouti', 'Djibouti', 'Africa'],
  ['Egypt', 'Egypt', 'Africa'],
  ['Equatorial Guinea', 'Eq. Guinea', 'Africa'],
  ['Eritrea', 'Eritrea', 'Africa'],
  ['Eswatini', 'eSwatini', 'Africa', ['Swaziland']],
  ['Ethiopia', 'Ethiopia', 'Africa'],
  ['Gabon', 'Gabon', 'Africa'],
  ['Gambia', 'Gambia', 'Africa'],
  ['Ghana', 'Ghana', 'Africa'],
  ['Guinea', 'Guinea', 'Africa'],
  ['Guinea-Bissau', 'Guinea-Bissau', 'Africa'],
  ["Côte d'Ivoire", "Côte d'Ivoire", 'Africa', ['Ivory Coast']],
  ['Kenya', 'Kenya', 'Africa'],
  ['Lesotho', 'Lesotho', 'Africa'],
  ['Liberia', 'Liberia', 'Africa'],
  ['Libya', 'Libya', 'Africa'],
  ['Madagascar', 'Madagascar', 'Africa'],
  ['Malawi', 'Malawi', 'Africa'],
  ['Mali', 'Mali', 'Africa'],
  ['Mauritania', 'Mauritania', 'Africa'],
  ['Mauritius', 'Mauritius', 'Africa'],
  ['Morocco', 'Morocco', 'Africa'],
  ['Mozambique', 'Mozambique', 'Africa'],
  ['Namibia', 'Namibia', 'Africa'],
  ['Niger', 'Niger', 'Africa'],
  ['Nigeria', 'Nigeria', 'Africa'],
  ['Rwanda', 'Rwanda', 'Africa'],
  ['São Tomé and Príncipe', 'São Tomé and Principe', 'Africa', ['Sao Tome']],
  ['Senegal', 'Senegal', 'Africa'],
  ['Seychelles', 'Seychelles', 'Africa'],
  ['Sierra Leone', 'Sierra Leone', 'Africa'],
  ['Somalia', 'Somalia', 'Africa'],
  ['South Africa', 'South Africa', 'Africa'],
  ['South Sudan', 'S. Sudan', 'Africa'],
  ['Sudan', 'Sudan', 'Africa'],
  ['Tanzania', 'Tanzania', 'Africa'],
  ['Togo', 'Togo', 'Africa'],
  ['Tunisia', 'Tunisia', 'Africa'],
  ['Uganda', 'Uganda', 'Africa'],
  ['Zambia', 'Zambia', 'Africa'],
  ['Zimbabwe', 'Zimbabwe', 'Africa'],

  // ── Asia ──
  ['Afghanistan', 'Afghanistan', 'Asia'],
  ['Armenia', 'Armenia', 'Asia'],
  ['Azerbaijan', 'Azerbaijan', 'Asia'],
  ['Bahrain', 'Bahrain', 'Asia'],
  ['Bangladesh', 'Bangladesh', 'Asia'],
  ['Bhutan', 'Bhutan', 'Asia'],
  ['Brunei', 'Brunei', 'Asia', ['Brunei Darussalam']],
  ['Cambodia', 'Cambodia', 'Asia'],
  ['China', 'China', 'Asia'],
  ['Georgia', 'Georgia', 'Asia'],
  ['India', 'India', 'Asia'],
  ['Indonesia', 'Indonesia', 'Asia'],
  ['Iran', 'Iran', 'Asia'],
  ['Iraq', 'Iraq', 'Asia'],
  ['Israel', 'Israel', 'Asia'],
  ['Japan', 'Japan', 'Asia'],
  ['Jordan', 'Jordan', 'Asia'],
  ['Kazakhstan', 'Kazakhstan', 'Asia'],
  ['Kuwait', 'Kuwait', 'Asia'],
  ['Kyrgyzstan', 'Kyrgyzstan', 'Asia', ['Kyrgyz Republic']],
  ['Laos', 'Laos', 'Asia', ['Lao']],
  ['Lebanon', 'Lebanon', 'Asia'],
  ['Malaysia', 'Malaysia', 'Asia'],
  ['Maldives', 'Maldives', 'Asia'],
  ['Mongolia', 'Mongolia', 'Asia'],
  ['Myanmar', 'Myanmar', 'Asia', ['Burma']],
  ['Nepal', 'Nepal', 'Asia'],
  ['North Korea', 'North Korea', 'Asia', ['DPRK', 'N Korea']],
  ['Oman', 'Oman', 'Asia'],
  ['Pakistan', 'Pakistan', 'Asia'],
  ['Palestine', 'Palestine', 'Asia', ['State of Palestine', 'Palestinian Territories']],
  ['Philippines', 'Philippines', 'Asia'],
  ['Qatar', 'Qatar', 'Asia'],
  ['Saudi Arabia', 'Saudi Arabia', 'Asia'],
  ['Singapore', 'Singapore', 'Asia'],
  ['South Korea', 'South Korea', 'Asia', ['Republic of Korea', 'S Korea']],
  ['Sri Lanka', 'Sri Lanka', 'Asia'],
  ['Syria', 'Syria', 'Asia'],
  ['Taiwan', 'Taiwan', 'Asia', ['Republic of China']],
  ['Tajikistan', 'Tajikistan', 'Asia'],
  ['Thailand', 'Thailand', 'Asia'],
  ['Timor-Leste', 'Timor-Leste', 'Asia', ['East Timor']],
  ['Turkey', 'Turkey', 'Asia', ['Türkiye']],
  ['Turkmenistan', 'Turkmenistan', 'Asia'],
  ['United Arab Emirates', 'United Arab Emirates', 'Asia', ['UAE', 'Emirates']],
  ['Uzbekistan', 'Uzbekistan', 'Asia'],
  ['Vietnam', 'Vietnam', 'Asia', ['Viet Nam']],
  ['Yemen', 'Yemen', 'Asia'],

  // ── Europe ──
  ['Albania', 'Albania', 'Europe'],
  ['Andorra', 'Andorra', 'Europe'],
  ['Austria', 'Austria', 'Europe'],
  ['Belarus', 'Belarus', 'Europe'],
  ['Belgium', 'Belgium', 'Europe'],
  ['Bosnia and Herzegovina', 'Bosnia and Herz.', 'Europe', ['Bosnia', 'BiH']],
  ['Bulgaria', 'Bulgaria', 'Europe'],
  ['Croatia', 'Croatia', 'Europe'],
  ['Cyprus', 'Cyprus', 'Europe'],
  ['Czechia', 'Czechia', 'Europe', ['Czech Republic']],
  ['Denmark', 'Denmark', 'Europe'],
  ['Estonia', 'Estonia', 'Europe'],
  ['Finland', 'Finland', 'Europe'],
  ['France', 'France', 'Europe'],
  ['Germany', 'Germany', 'Europe'],
  ['Greece', 'Greece', 'Europe'],
  ['Hungary', 'Hungary', 'Europe'],
  ['Iceland', 'Iceland', 'Europe'],
  ['Ireland', 'Ireland', 'Europe', ['Republic of Ireland']],
  ['Italy', 'Italy', 'Europe'],
  ['Kosovo', 'Kosovo', 'Europe'],
  ['Latvia', 'Latvia', 'Europe'],
  ['Liechtenstein', 'Liechtenstein', 'Europe'],
  ['Lithuania', 'Lithuania', 'Europe'],
  ['Luxembourg', 'Luxembourg', 'Europe'],
  ['Malta', 'Malta', 'Europe'],
  ['Moldova', 'Moldova', 'Europe'],
  ['Monaco', 'Monaco', 'Europe'],
  ['Montenegro', 'Montenegro', 'Europe'],
  ['Netherlands', 'Netherlands', 'Europe', ['Holland']],
  ['North Macedonia', 'Macedonia', 'Europe', ['Macedonia']],
  ['Norway', 'Norway', 'Europe'],
  ['Poland', 'Poland', 'Europe'],
  ['Portugal', 'Portugal', 'Europe'],
  ['Romania', 'Romania', 'Europe'],
  ['Russia', 'Russia', 'Europe', ['Russian Federation']],
  ['San Marino', 'San Marino', 'Europe'],
  ['Serbia', 'Serbia', 'Europe'],
  ['Slovakia', 'Slovakia', 'Europe'],
  ['Slovenia', 'Slovenia', 'Europe'],
  ['Spain', 'Spain', 'Europe'],
  ['Sweden', 'Sweden', 'Europe'],
  ['Switzerland', 'Switzerland', 'Europe'],
  ['Ukraine', 'Ukraine', 'Europe'],
  ['United Kingdom', 'United Kingdom', 'Europe', ['UK', 'Great Britain', 'Britain']],
  ['Vatican City', 'Vatican', 'Europe', ['Vatican', 'Holy See']],

  // ── North America (incl. Central America & the Caribbean) ──
  ['Antigua and Barbuda', 'Antigua and Barb.', 'North America', ['Antigua']],
  ['Bahamas', 'Bahamas', 'North America'],
  ['Barbados', 'Barbados', 'North America'],
  ['Belize', 'Belize', 'North America'],
  ['Canada', 'Canada', 'North America'],
  ['Costa Rica', 'Costa Rica', 'North America'],
  ['Cuba', 'Cuba', 'North America'],
  ['Dominica', 'Dominica', 'North America'],
  ['Dominican Republic', 'Dominican Rep.', 'North America', ['Dominican Rep']],
  ['El Salvador', 'El Salvador', 'North America'],
  ['Grenada', 'Grenada', 'North America'],
  ['Guatemala', 'Guatemala', 'North America'],
  ['Haiti', 'Haiti', 'North America'],
  ['Honduras', 'Honduras', 'North America'],
  ['Jamaica', 'Jamaica', 'North America'],
  ['Mexico', 'Mexico', 'North America'],
  ['Nicaragua', 'Nicaragua', 'North America'],
  ['Panama', 'Panama', 'North America'],
  ['Saint Kitts and Nevis', 'St. Kitts and Nevis', 'North America', ['Saint Kitts']],
  ['Saint Lucia', 'Saint Lucia', 'North America'],
  ['Saint Vincent and the Grenadines', 'St. Vin. and Gren.', 'North America', ['Saint Vincent', 'Grenadines']],
  ['Trinidad and Tobago', 'Trinidad and Tobago', 'North America', ['Trinidad']],
  ['United States', 'United States of America', 'North America', ['United States of America', 'USA', 'US', 'America']],

  // ── South America ──
  ['Argentina', 'Argentina', 'South America'],
  ['Bolivia', 'Bolivia', 'South America'],
  ['Brazil', 'Brazil', 'South America'],
  ['Chile', 'Chile', 'South America'],
  ['Colombia', 'Colombia', 'South America'],
  ['Ecuador', 'Ecuador', 'South America'],
  ['Guyana', 'Guyana', 'South America'],
  ['Paraguay', 'Paraguay', 'South America'],
  ['Peru', 'Peru', 'South America'],
  ['Suriname', 'Suriname', 'South America'],
  ['Uruguay', 'Uruguay', 'South America'],
  ['Venezuela', 'Venezuela', 'South America'],

  // ── Oceania ──
  ['Australia', 'Australia', 'Oceania'],
  ['Fiji', 'Fiji', 'Oceania'],
  ['Kiribati', 'Kiribati', 'Oceania'],
  ['Marshall Islands', 'Marshall Is.', 'Oceania'],
  ['Micronesia', 'Micronesia', 'Oceania', ['Federated States of Micronesia', 'FSM']],
  ['Nauru', 'Nauru', 'Oceania'],
  ['New Zealand', 'New Zealand', 'Oceania'],
  ['Palau', 'Palau', 'Oceania'],
  ['Papua New Guinea', 'Papua New Guinea', 'Oceania', ['PNG']],
  ['Samoa', 'Samoa', 'Oceania', ['Western Samoa']],
  ['Solomon Islands', 'Solomon Is.', 'Oceania', ['Solomons']],
  ['Tonga', 'Tonga', 'Oceania'],
  ['Tuvalu', null, 'Oceania'], // missing from the 50m data — drawn from hand-placed atolls in build-data.mjs
  ['Vanuatu', 'Vanuatu', 'Oceania'],
];
